name: Build and Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare files (frontend + jar)
        run: ./utilities/build-files.sh "${{ github.ref_name }}"

      - name: Build & Push Docker image
        working-directory: server
        run: |
          IMAGE_VERSION="${{ github.ref_name }}"
          DOCKER_REPO="bingud/filemat"
          IMAGE_TAG="$DOCKER_REPO:$IMAGE_VERSION"
          LATEST_TAG="$DOCKER_REPO:latest"

          docker build -t "$IMAGE_TAG" -t "$LATEST_TAG" -f Dockerfile .
          docker push "$IMAGE_TAG"
          docker push "$LATEST_TAG"